version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: campaign-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campaign_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d campaign_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: campaign-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

#  app:
#    build: .
#    container_name: campaign-app
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/campaign_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
